n_iter: 10_000
seed: 42

env:
  fp16: true
  n_gpu: 1

loader:
  batch_size: 128
  num_workers: 10
  pin_memory: true
  drop_last: true

optim:
  name: adamw
  lr: 3e-4

scheduler:
  name: cycle
  n_iter: 10_000
  warmup: 100
  decay: lin, cos

dataset:
  path: data
  height: 19
  width: 24
  window_size: 48
  hop_size: 1